GSTREAMER PLUGINS BAD: revert part of (gtk)waylandsink: fix QVGA YUV420 planar
This cause issue with
gst-launch-1.0 libcamerasrc  ! video/x-raw, format=RGB16, width=800, height=600 ! queue ! waylandsink
zwp_linux_buffer_params_v1@14: error 6: invalid buffer stride or height for plane 0
ERROR: from element /GstPipeline:pipeline0/GstWaylandSink:waylandsink0: Video memory can not be read from userspace.

Change-Id: Ic82e3787dd74642426baea3d35c2d778f4b1da14
Signed-off-by: Hugues Fruchet <hugues.fruchet@foss.st.com>
Reviewed-on: https://gerrit.st.com/c/oeivi/oe/st/meta-opensdk/+/435172
ACI: CITOOLS <MDG-smet-aci-reviews@list.st.com>
Tested-by: Christophe PRIOUZEAU <christophe.priouzeau@st.com>
Reviewed-by: Christophe PRIOUZEAU <christophe.priouzeau@st.com>